#!/usr/bin/env python3
"""
Universal Safe Strip for Unreal Engine Blueprint Exports

Removes editor-only data from any UEdGraph-based asset while preserving
all semantic information. Unknown fields are kept (safe side).

Can be used standalone:
    python strip_utils.py <input_file>
    -> produces <basename>_stripped.txt

Or imported by simplifiers:
    from strip_utils import safe_strip, strip_file
"""

import re
import sys
import os


# ---------------------------------------------------------------------------
#  Line-level skip patterns
# ---------------------------------------------------------------------------

_SKIP_LINE_PREFIXES = (
    'NodePosX=',
    'NodePosY=',
    'NodeGuid=',
    'ErrorType=',
    'ErrorMsg=',
    'EnabledState=',
    'NodeComment=',
    'ShowPinForProperties(',
)

_SKIP_LINE_EXACT = frozenset({'End Object'})


# ---------------------------------------------------------------------------
#  Pin-line removal patterns (compiled for performance)
# ---------------------------------------------------------------------------

_PIN_REMOVE_PATTERNS = [
    re.compile(p) for p in [
        # Pin tracking IDs
        r'PinId=[A-F0-9]+',
        r'PersistentGuid=[A-F0-9]+',

        # 6x editor bool flags
        r'bHidden=(?:True|False)',
        r'bNotConnectable=(?:True|False)',
        r'bDefaultValueIsReadOnly=(?:True|False)',
        r'bDefaultValueIsIgnored=(?:True|False)',
        r'bAdvancedView=(?:True|False)',
        r'bOrphanedPin=(?:True|False)',

        # 8x PinType boilerplate
        r'PinType\.PinSubCategory=""',
        r'PinType\.PinSubCategoryObject=[^\s,)]+',
        r'PinType\.PinSubCategoryMemberReference=\([^)]*\)',
        r'PinType\.PinValueType=\([^)]*\)',
        r'(?:PinType\.)?ContainerType=None',
        r'(?:PinType\.)?bIsReference=False',
        r'(?:PinType\.)?bIsConst=False',
        r'(?:PinType\.)?bIsWeakPointer=False',

        # Editor auto-fill value
        r'AutogeneratedDefaultValue="(?:[^"\\]|\\.)*"',

        # Tooltip (can be very long, may contain escaped quotes)
        r'PinToolTip="(?:[^"\\]|\\.)*"',
    ]
]

# LinkedTo hex GUID cleanup: remove " <32-char-hex>" after node names
_LINKED_HEX_RE = re.compile(r'\s+[A-F0-9]{20,}')

# Path shortening patterns
_EXPORT_PATH_RE = re.compile(r'\s*ExportPath="[^"]*"')
_SCRIPT_PATH_FULL_RE = re.compile(
    r"/Script/\w+\.\w+'/Script/\w+\.(\w+)'"
)
_SCRIPT_PATH_SIMPLE_RE = re.compile(r'/Script/\w+\.(\w+)')

# Collapse multiple consecutive blank lines
_MULTI_BLANK_RE = re.compile(r'\n{3,}')


# ---------------------------------------------------------------------------
#  Public API
# ---------------------------------------------------------------------------

def safe_strip(content: str) -> str:
    """Universal safe strip for all UEdGraph-based assets.

    Removes editor-only data while preserving all semantic information.
    Unknown fields are kept (safe side).

    Returns the stripped content as a string.
    """
    lines = content.splitlines()
    output_lines = []
    prev_blank = False

    for line in lines:
        stripped = line.strip()

        # Collapse consecutive blank lines
        if not stripped:
            if not prev_blank:
                output_lines.append('')
                prev_blank = True
            continue
        prev_blank = False

        # Line-level removals
        if _should_skip_line(stripped):
            continue

        # Pin line cleanup
        if stripped.startswith('CustomProperties Pin ('):
            line = _clean_pin_line(line)
            # If line became empty after cleanup, skip
            clean_check = line.strip()
            if not clean_check or clean_check == 'CustomProperties Pin ()':
                continue

        # Path shortening (all lines)
        line = _shorten_paths(line)

        output_lines.append(line)

    result = '\n'.join(output_lines)
    # Final pass: collapse any 3+ consecutive newlines to 2
    result = _MULTI_BLANK_RE.sub('\n\n', result)
    return result


def strip_file(input_path: str) -> str:
    """Strip a file and write the output. Returns the output path."""
    with open(input_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    original_size = len(content)
    stripped = safe_strip(content)

    # Build output path
    base_name = os.path.splitext(input_path)[0]
    if base_name.endswith('_raw'):
        base_name = base_name[:-4]
    output_path = f"{base_name}_stripped.txt"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(stripped)

    stripped_size = len(stripped)
    print(f"Stripped: {input_path}")
    print(f"  Original: {original_size:,} bytes")
    print(f"  Stripped:  {stripped_size:,} bytes")
    if original_size > 0:
        print(f"  Reduction: {(1 - stripped_size / original_size) * 100:.1f}%")
    print(f"  Output: {output_path}")

    return output_path


# ---------------------------------------------------------------------------
#  Internal helpers
# ---------------------------------------------------------------------------

def _should_skip_line(stripped: str) -> bool:
    """Check if an entire line should be removed."""
    if stripped in _SKIP_LINE_EXACT:
        return True
    for prefix in _SKIP_LINE_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False


def _clean_pin_line(line: str) -> str:
    """Clean editor-only data from a CustomProperties Pin line."""
    for pattern in _PIN_REMOVE_PATTERNS:
        line = pattern.sub('', line)

    # Clean LinkedTo hex GUIDs: "NodeName ABC123DEF..." -> "NodeName"
    def _clean_linked(m):
        inner = m.group(1)
        cleaned = _LINKED_HEX_RE.sub('', inner)
        return f'LinkedTo=({cleaned})'

    line = re.sub(r'LinkedTo=\(([^)]+)\)', _clean_linked, line)

    # Collapse multiple spaces into one
    line = re.sub(r'  +', ' ', line)

    return line


def _shorten_paths(line: str) -> str:
    """Shorten UE asset paths to just class names."""
    # Remove ExportPath="..." entirely
    line = _EXPORT_PATH_RE.sub('', line)

    # Shorten nested paths: /Script/X.Type'/Script/Y.Class' -> Class
    line = _SCRIPT_PATH_FULL_RE.sub(r'\1', line)

    # Shorten simple paths: /Script/X.Class -> Class
    line = _SCRIPT_PATH_SIMPLE_RE.sub(r'\1', line)

    return line


# ---------------------------------------------------------------------------
#  Standalone CLI
# ---------------------------------------------------------------------------

def main():
    """Standalone entry point for stripping any UE asset export."""
    if len(sys.argv) < 2:
        print("Usage: python strip_utils.py <input_file>")
        print("  Produces <basename>_stripped.txt")
        print()
        print("Removes editor-only data (positions, GUIDs, pin boilerplate,")
        print("tooltips, etc.) while preserving all semantic information.")
        sys.exit(1)

    input_file = sys.argv[1]
    if not os.path.exists(input_file):
        print(f"Error: File not found: {input_file}")
        sys.exit(1)

    strip_file(input_file)


if __name__ == "__main__":
    main()
